<a href="https://colab.research.google.com/github/prasannaas138-alt/youtube-recommendation-system/blob/main/Youtube_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/youtube_videos.csv')

In [ ]:
df.shape

(5000, 8)

In [ ]:
df.head()

,video_id,title,category,description,tags,channel,views,likes
0,V03407,SQL for Beginners Explained for Beginners,SQL,This video breaks down sql for beginners into ...,"indexing, database, sql, sql for beginners, jo...",Quantum Coders,837156,19218
1,V00758,Data Science Projects Best Practices,Data Science,"In this tutorial, we explore data science proj...","dataset, data, insights, tutorial, statistics,...",PeakProductivity,43330,3875
2,V03625,Mastering Building Scalable Cloud Applications...,Cloud Computing,We take a deep dive into building scalable clo...,"howto, cloud computing, virtual machines, buil...",LearnWithCode,298869,27734
3,V04545,Self-Taught Developer Roadmap Made Simple,Education,This video breaks down self-taught developer r...,"study tips, skill building, self-improvement, ...",FutureTech Studio,271653,18951
4,V03236,Node.js Basics Deep Dive,Node.js,"We take a deep dive into node.js basics, cover...","node.js, api, html, express, walkthrough, node...",Quantum Coders,5392,337

In [ ]:
df.columns

Index(['video_id', 'title', 'category', 'description', 'tags', 'channel',
       'views', 'likes'],
      dtype='object')

In [ ]:
df.isnull().sum()

video_id       0
title          0
category       0
description    0
tags           0
channel        0
views          0
likes          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['video_id'].nunique()

5000

In [ ]:
df['category'].nunique()

30

In [ ]:
df['category'].value_counts()

category
Python                         405
Data Science                   380
Machine Learning               380
Web Development                287
Artificial Intelligence        253
Deep Learning                  220
Programming                    203
Generative AI                  177
React                          177
SQL                            177
JavaScript                     177
Natural Language Processing    160
Computer Vision                160
Cloud Computing                135
Cybersecurity                  135
Technology                     135
Node.js                        135
Gaming                         135
DevOps                         110
UI/UX Design                   110
Career                         110
Database                       110
Fitness                         96
Education                       93
Productivity                    93
Photography                     93
Git & GitHub                    93
Music                           93
CSS                             84
HTML                            84
Name: count, dtype: int64

In [ ]:
df[['views','likes']].describe()

              views          likes
count  5.000000e+03    5000.000000
mean   1.392694e+05    8825.077400
std    3.873113e+05   27051.189948
min    1.000000e+03      14.000000
25%    1.242675e+04     670.000000
50%    3.706800e+04    2061.000000
75%    1.107460e+05    6508.500000
max    6.000000e+06  698788.000000

In [ ]:
text_columns = ['title','description','tags','category']

for column in text_columns:
  df[column] = df[column].fillna("").astype(str)

In [ ]:
df['combined_text'] = (
    df['title'] + " " +
    df['description'] + " " +
    df['tags'] + " " +
    df['category']
)

In [ ]:
df[['title' , 'combined_text']].head()

,title,combined_text
0,SQL for Beginners Explained for Beginners,SQL for Beginners Explained for Beginners This...
1,Data Science Projects Best Practices,Data Science Projects Best Practices In this t...
2,Mastering Building Scalable Cloud Applications...,Mastering Building Scalable Cloud Applications...
3,Self-Taught Developer Roadmap Made Simple,Self-Taught Developer Roadmap Made Simple This...
4,Node.js Basics Deep Dive,Node.js Basics Deep Dive We take a deep dive i...

In [ ]:
df[['video_id' , 'title' , 'combined_text']].head()

,video_id,title,combined_text
0,V03407,SQL for Beginners Explained for Beginners,SQL for Beginners Explained for Beginners This...
1,V00758,Data Science Projects Best Practices,Data Science Projects Best Practices In this t...
2,V03625,Mastering Building Scalable Cloud Applications...,Mastering Building Scalable Cloud Applications...
3,V04545,Self-Taught Developer Roadmap Made Simple,Self-Taught Developer Roadmap Made Simple This...
4,V03236,Node.js Basics Deep Dive,Node.js Basics Deep Dive We take a deep dive i...

In [ ]:
df['combined_text'].dtype

dtype('O')

In [ ]:
df['combined_text'] = df['combined_text'].str.lower()

In [ ]:
df['combined_text'] = df['combined_text'].str.replace(r"\s+" , " " , regex = True).str.strip()

In [ ]:
df[['title' , 'combined_text']].head()

,title,combined_text
0,SQL for Beginners Explained for Beginners,sql for beginners explained for beginners this...
1,Data Science Projects Best Practices,data science projects best practices in this t...
2,Mastering Building Scalable Cloud Applications...,mastering building scalable cloud applications...
3,Self-Taught Developer Roadmap Made Simple,self-taught developer roadmap made simple this...
4,Node.js Basics Deep Dive,node.js basics deep dive we take a deep dive i...